const notifyUsers = (req, res) =>{
    try {
        
    } catch (e) {
        res.status(500).send("Error occured "+ e.message )
    }
}